### ISSUE TITLE
`f0` passed has more than 1 dimension

### ISSUE THREAD

**Issue by skbhat** [plgreenLIRU/Gaussian-Process-SparseGP-Tutorial#2]
Namaste,

Thanks for the well commented code on a tough topic.  With latest version of scipy one may get this error.  It can be fixed by following minor change:

In the function NegLowerBound in LIRU_SparseGP.py change the following line

_return NLB_  

to 

_return NLB.ravel()_

regards
skbhat

**Comment by plgreenLIRU** [comment]
> Namaste,
> 
> Thanks for the well commented code on a tough topic. With latest version of scipy one may get this error. It can be fixed by following minor change:
> 
> In the function NegLowerBound in LIRU_SparseGP.py change the following line
> 
> _return NLB_
> 
> to
> 
> _return NLB.ravel()_
> 
> regards
> skbhat

Ah great thanks for letting me know. I haven't looked at this for a long time and forgot it existed! Would you like to do a PR? Happy to take care of it otherwise.

**Comment by skbhat** [comment]
I am not very good at git related stuffs.  Moreover, the change is very very minor.  Please go ahead.

regards
skbhat

**Comment by plgreenLIRU** [comment]
Sorted; thanks again
